; SPDX-License-Identifier: MIT
; Copyright (c) 2025 InstaChord Corp.
;
; EXTIO2 I2C Address Rewrite Tool

[env:cores3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = m5stack-cores3
framework = arduino

lib_deps =
    M5Stack/M5Unified

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
